Repository karimmekdoud/BDD_Selenium_Automation_Framework_Team4, pull requests merged in 2020-06, with the labels that each got.

#2 1st commit
  Amazon/src/main/java/home/AmazonWebElements.java
  Amazon/src/main/java/home/HomePage.java
  Amazon/src/main/java/step_definitions/HomePage_StepDefinition.java
  Amazon/src/test/java/runner/TestRunner.java
  Booking/src/main/java/features/HomePage.feature
  Booking/src/main/java/home/BookingWebElements.java
  Booking/src/main/java/step_definitions/HomePage_StepDefinition.java
  Booking/src/test/java/runner/TestRunner.java
  Empire/src/main/java/features/HomePage.feature
  Empire/src/main/java/home/EmpireWebElements.java
  Empire/src/main/java/step_definitions/HomePage_StepDefinition.java
  Empire/src/test/java/runner/TestRunner.java
  Geico/src/main/java/features/HomePage.feature
  Geico/src/main/java/home/GeicoWebElements.java
  Geico/src/main/java/step_definitions/HomePage_StepDefinition.java
  Geico/src/test/java/runner/TestRunner.java
  Generic/secret.properties
  Generic/src/main/java/common/WebAPI.java
  Generic/src/main/java/dataBase/ConnectToSqlDB.java
  Generic/src/main/java/utility/DataReader.java
  Generic/src/main/java/utility/DataReader1.java
  Generic/src/main/java/utility/DataReader2.java
  Netflix/src/main/java/features/HomePage.feature
  Netflix/src/main/java/home/NetflixWebElements.java
  Netflix/src/main/java/step_definitions/HomePage_StepDefinition.java
  Netflix/src/test/java/runner/TestRunner.java
  Sprint/src/main/java/features/HomePage.feature
  Sprint/src/main/java/home/SprintWebElements.java
  Sprint/src/main/java/step_definitions/HomePage_StepDefinition.java
  Sprint/src/test/java/runner/TestRunner.java
  TD_Bank/src/main/java/features/HomePage.feature
  TD_Bank/src/main/java/home/TD_BankWebElements.java
  TD_Bank/src/main/java/step_definitions/HomePage_StepDefinition.java
  TD_Bank/src/test/java/runner/TestRunner.java
  United/src/main/java/features/HomePage.feature
  United/src/main/java/home/UnitedWebElements.java
  United/src/main/java/step_definitions/HomePage_StepDefinition.java
  United/src/test/java/runner/TestRunner.java
Labels: enhancement

#4 my first commit
  Amazon/target/cucumber-reports/cucumber.json
  Amazon/target/cucumber-reports/formatter.js
  Amazon/target/cucumber-reports/index.html
  Amazon/target/cucumber-reports/jquery-3.4.1.min.js
  Amazon/target/cucumber-reports/report.js
  Amazon/target/cucumber-reports/style.css
  Booking/src/main/test/java/runner/TestRunner.java
  Empire/src/main/test/java/runner/TestRunner.java
  Geico/src/main/test/java/runner/TestRunner.java
  Generic/src/main/java/common/WebAPI.java
  Netflix/src/main/test/java/runner/TestRunner.java
  Sprint/src/main/test/java/runner/TestRunner.java
  TD_Bank/src/main/test/java/runner/TestRunner.java
  United/src/main/test/java/runner/TestRunner.java
Labels: bug

#11 80 test cases completed
  Amazon/src/main/java/features/HomePage.feature
  Amazon/src/main/java/home/AmazonWebElements.java
  Amazon/src/main/java/home/HomePage.java
  Amazon/src/main/java/step_definitions/HomePage_StepDefinition.java
  Amazon/src/test/java/runner/TestRunner.java
  Booking/src/main/java/features/HomePage.feature
  Booking/src/main/java/home/BookingWebElements.java
  Booking/src/main/java/home/HomePage.java
  Booking/src/main/java/step_Definitions/Homepage_StepDefinition.java
  Booking/src/test/java/runner/TestRunner.java
  Empire/src/main/java/features/HomePage.feature
  Empire/src/main/java/home/HomePage.java
  Empire/src/main/java/java/features/HomePage.feature
  Empire/src/main/java/java/home/EmpireWebElements.java
  Empire/src/main/java/java/home/HomePage.java
  Empire/src/main/java/java/step_Definitions/Homepage_StepDefinition.java
  Empire/src/main/java/step_Definitions/Homepage_StepDefinition.java
  Empire/src/test/java/runner/TestRunner.java
  Geico/src/main/java/features/HomePage.feature
  Geico/src/main/java/home/GeicoWebElement.java
  Geico/src/main/java/home/HomePage.java
  Geico/src/main/java/java/features/HomePage.feature
  Geico/src/main/java/java/home/GeicoWebElements.java
  Geico/src/main/java/java/home/HomePage.java
  Geico/src/main/java/java/step_Definitions/Homepage_StepDefinition.java
  Geico/src/main/java/step_Definitions/Homepage_StepDefinition.java
  Generic/secret.properties
  Generic/src/main/java/common/WebAPI.java
  Generic/src/main/java/dataBase/ConnectToSqlDB.java
  Generic/src/main/java/dataBase/User.java
  Generic/src/main/java/dataBase/user2.java
  Netflix/src/main/java/features/HomePage.feature
  Netflix/src/main/java/home/HomePage.java
  Netflix/src/main/java/home/NetflixWebElement.java
  Netflix/src/main/java/java/features/HomePage.feature
  Netflix/src/main/java/java/home/HomePage.java
  Netflix/src/main/java/java/home/NetflixWebElements.java
  Netflix/src/main/java/java/step_Definitions/Homepage_StepDefinition.java
  Netflix/src/main/java/step_Definitions/Homepage_StepDefinition.java
  Netflix/src/test/java/runner/TestRunner.java
  Sprint/src/main/java/features/HomePage.feature
  Sprint/src/main/java/home/HomePage.java
  Sprint/src/main/java/home/SprintWebElements.java
  Sprint/src/main/java/java/features/HomePage.feature
  Sprint/src/main/java/java/home/HomePage.java
  Sprint/src/main/java/java/home/SprintWebElements.java
  Sprint/src/main/java/java/step_Definitions/Homepage_StepDefinition.java
  Sprint/src/main/java/step_Definitions/Homepage_StepDefinition.java
  Sprint/src/test/java/runner/TestRunner.java
  TD_Bank/src/main/java/java/home/TD_BankWebElements.java
  United/src/main/java/features/HomePage.feature
  United/src/main/java/home/HomePage.java
  United/src/main/java/home/UnitedWebElement.java
  United/src/main/java/java/features/HomePage.feature
  United/src/main/java/java/home/HomePage.java
  United/src/main/java/java/home/UnitedWebElements.java
  United/src/main/java/java/step_Definitions/Homepage_StepDefinition.java
  United/src/main/java/step_Definitions/Homepage_StepDefinition.java
  United/src/test/java/runner/TestRunner.java
  pom.xml
Labels: enhancement

#10 50 test done finally
  Amazon/src/main/java/features/HomePage.feature
  Amazon/src/main/java/home/AmazonWebElements.java
  Amazon/src/main/java/home/HomePage.java
  Amazon/src/main/java/step_definitions/HomePage_StepDefinition.java
  Amazon/target/cucumber-reports/cucumber.json
  Amazon/target/cucumber-reports/report.js
  Booking/src/main/java/features/HomePage.feature
  Booking/src/main/java/home/BookingWebElements.java
  Booking/src/main/java/home/HomePage.java
  Booking/src/main/java/home/WebElements.java
  Booking/src/main/java/step_definitions/HomePage_StepDefinition.java
  Geico/src/main/java/features/HomePage.feature
  Geico/src/main/java/home/HomePage.java
  Geico/src/main/java/home/WebElements.java
  Geico/src/main/java/step_definitions/HomePage_StepDefinition.java
  Geico/target/cucumber-reports/cucumber.json
  Geico/target/cucumber-reports/report.js
  Generic/pom.xml
  Generic/secret.properties
  Generic/src/main/java/common/WebAPI.java
  Generic/src/main/java/dataBase/ConnectToSqlDB.java
  Generic/src/main/java/dataBase/UnitedList.java
  Netflix/src/main/java/features/HomePage.feature
  Netflix/src/main/java/home/HomePage.java
  Netflix/src/main/java/home/WebElements.java
  Netflix/src/main/java/step_definitions/HomePage_StepDefinition.java
  Netflix/target/cucumber-reports/cucumber.json
  Netflix/target/cucumber-reports/report.js
  United/src/main/java/features/HomePage.feature
  United/src/main/java/home/HomePage.java
  United/src/main/java/home/WebElements.java
  United/src/main/java/step_definitions/HomePage_StepDefinition.java
  United/target/cucumber-reports/cucumber.json
  United/target/cucumber-reports/report.js
Labels: bug, documentation, duplicate, enhancement, good first issue, help wanted, invalid, question, wontfix

#17 my 60 test cases BDD COMPLITED
  Amazon/src/main/java/features/HomePage.feature
  Amazon/src/main/java/home/AmazonWebElements.java
  Amazon/src/main/java/home/HomePage.java
  Amazon/src/main/java/step_definitions/HomePage_StepDefinition.java
Labels: documentation
